"""empty message

Revision ID: 3a5b69209b87
Revises: 9b1a5f643c4f
Create Date: 2020-03-28 18:45:35.776603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a5b69209b87"
down_revision = "9b1a5f643c4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
