"""empty message

Revision ID: 9b1a5f643c4f
Revises: 
Create Date: 2020-03-28 18:28:37.829034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1a5f643c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=100, collation='utf8_unicode_ci'), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_item')
    # ### end Alembic commands ###
